// orchestrate.js — The main refresh runner for the Living Book v2.
//
// Refreshes the answer for ONE question at a time. It fetches a fresh
// answer (either a deterministic mock, or — in live mode — from the
// Abacus.AI API), records it as a new claim, bumps the question's edition,
// appends an immutable ledger entry, and logs every action.
//
// Usage:
//   node scripts/orchestrate.js --question-id q001 --mock   # safe, offline
//   node scripts/orchestrate.js --question-id q001          # live (needs key)
//
// Live mode reads the API key from process.env.ABACUS_API_KEY ONLY.
// No credential is ever written to disk or hardcoded here.

const fs = require("fs");
const path = require("path");
const {
  PATHS,
  readJSON,
  writeJSON,
  today,
  nowISO,
  classifySource,
  summarise,
} = require("./lib.js");
const { parseArgs } = require("./propose-question.js");
const { runEnsemble } = require("./agents/ensemble.js");

// ── Logging ─────────────────────────────────────────────────────────
function log(message) {
  fs.mkdirSync(path.dirname(PATHS.orchestrationLog), { recursive: true });
  const line = `${nowISO()}  ${message}\n`;
  fs.appendFileSync(PATHS.orchestrationLog, line);
  return line;
}

// ── Fresh-answer providers ──────────────────────────────────────────
// MOCK: deterministic, offline, no network. Used by tests and dry-runs.
function mockAnswer(questionId, questionText) {
  return {
    text:
      `**[MOCK REFRESH]** This is a deterministic mock answer for ` +
      `${questionId}. In live mode this text would be generated by the ` +
      `Abacus.AI model in response to the question: "${questionText}". ` +
      `No network call was made.`,
    sources: [
      {
        title: "Mock source (orchestrator self-test)",
        url: "https://example.com/mock/" + questionId,
      },
    ],
    model: "mock",
  };
}

// LIVE: call the Abacus.AI API. Isolated so it is never exercised by tests.
async function liveAnswer(questionText) {
  const apiKey = process.env.ABACUS_API_KEY;
  if (!apiKey) {
    throw new Error(
      "ABACUS_API_KEY is not set. Provide it via the environment, " +
        "or run with --mock for an offline refresh."
    );
  }

  // OpenAI-compatible RouteLLM endpoint available on the Abacus.AI VM.
  const llmBase =
    process.env.ABACUS_LLM_BASE_URL ||
    process.env.ABACUS_API_ENDPOINT ||
    "https://routellm.abacus.ai/v1";
  const endpoint = llmBase.replace(/\/$/, "") + "/chat/completions";
  const model = process.env.ABACUS_MODEL || "claude-sonnet-4-6";

  // Read the canonical voice prompt from book.config.json so the live
  // API call always matches the book's editorial standard.
  let configVoicePrompt =
    "Write in clear, elegant, essayistic prose for an educated general reader. " +
    "Be precise and intellectually honest: distinguish established fact from open debate. " +
    "Avoid hype, avoid bullet points, avoid AI-sounding filler phrases. " +
    "Each answer should read as a self-contained, comprehensive essay of 700-900 words. " +
    "Never use first person.";
  try {
    const bookConfig = JSON.parse(
      require("fs").readFileSync(
        require("path").join(PATHS.root, "book.config.json"), "utf8"
      )
    );
    if (bookConfig.voicePrompt) configVoicePrompt = bookConfig.voicePrompt;
  } catch (_) { /* fall back to inline default */ }

  const systemPrompt =
    configVoicePrompt + "\n\n" +
    "You are writing one section of a living reference book on AI in Education. " +
    "Rules that override everything else:\n" +
    "1. Write a thorough, substantive essay — aim for 700-900 words of real depth.\n" +
    "2. Cover the full intellectual landscape: define key terms, explain the evidence, " +
    "   acknowledge contested areas, and draw a clear conclusion.\n" +
    "3. Every major factual claim should be grounded in real research or authoritative " +
    "   sources. Where possible, cite sources by naming them and including URLs.\n" +
    "4. If evidence is mixed or contested, say so plainly. Never manufacture certainty.\n" +
    "5. Do not mention that you are an AI, do not address the reader directly, " +
    "   and do not refer to these instructions.";

  const response = await fetch(endpoint, {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model,
      messages: [
        { role: "system", content: systemPrompt },
        {
          role: "user",
          content:
            "Write a comprehensive, well-sourced essay answering the following " +
            "question for the AI in Education living book. The essay must be " +
            "700-900 words, substantive, and intellectually rigorous.\n\n" +
            "Question: " + questionText,
        },
      ],
      max_tokens: 3000,
    }),
  });

  if (!response.ok) {
    throw new Error(
      `Abacus.AI API error ${response.status}: ${await response.text()}`
    );
  }

  const data = await response.json();
  // OpenAI-compatible response: choices[0].message.content
  const text =
    data?.choices?.[0]?.message?.content ||
    data?.result?.messages?.slice(-1)[0]?.text ||
    data?.result?.answer ||
    data?.answer ||
    (typeof data === "string" ? data : JSON.stringify(data));

  // RouteLLM does not return structured sources; extract URLs from the text.
  const urlRegex = /https?:\/\/[^\s)"']+/g;
  const urlMatches = String(text).match(urlRegex) || [];
  const sources = [...new Set(urlMatches)].slice(0, 8).map((url) => ({
    title: url,
    url,
  }));

  return { text: String(text).trim(), sources, model };
}

// ── Core refresh logic ──────────────────────────────────────────────
// Exported and testable. `provider` lets tests inject a fake fetcher.
async function orchestrate(
  questionId,
  {
    mock = false,
    provider = null,
    persist = true,
    ensemble = false,
    apiCall = null,
  } = {}
) {
  if (!questionId || !/^q\d+$/.test(questionId)) {
    throw new Error(`Invalid --question-id "${questionId}" (expected qNNN).`);
  }

  const mode = `${mock ? "mock" : "live"}${ensemble ? "+ensemble" : ""}`;
  log(`START refresh ${questionId} (mode=${mode})`);

  // 1. Confirm the question exists and is active in the registry.
  const registry = readJSON(PATHS.registry, null);
  if (!registry) {
    throw new Error(
      "Registry not found. Run `node scripts/migrate.js` first."
    );
  }
  const regEntry = registry.questions.find((q) => q.id === questionId);
  if (!regEntry) {
    log(`ABORT ${questionId}: not found in registry`);
    throw new Error(`Question ${questionId} is not in the registry.`);
  }
  if (regEntry.status === "deprecated") {
    log(`ABORT ${questionId}: deprecated`);
    throw new Error(`Question ${questionId} is deprecated; refusing to refresh.`);
  }

  // 2. Determine the next global edition number from the ledger.
  const ledger = readJSON(PATHS.ledger, { editions: [] });
  const maxEdition = ledger.editions.reduce(
    (m, e) => Math.max(m, e.edition_number || 0),
    0
  );
  const newEdition = maxEdition + 1;

  const claimFilePath = path.join(PATHS.claimsDir, `${questionId}.json`);
  const existing = readJSON(claimFilePath, null);
  const day = today();

  const claimFile = existing || {
    question_id: questionId,
    question_text: regEntry.question,
    current_edition: 0,
    claims: [],
    answer_summary: "",
    disputed_aspects: [],
  };

  let newClaims;

  if (ensemble) {
    // ── Multi-agent path: Research → Verification → Synthesis ────────
    const result = await runEnsemble({
      questionId,
      mock,
      edition: newEdition,
      apiCall,
      registryData: registry,
    });
    const synthesized = result.claimFile;
    if (!synthesized.claims.length) {
      log(`FAIL ${questionId}: ensemble produced no verified claims`);
      throw new Error("Ensemble produced no verified claims.");
    }
    // Renumber synthesized claims to continue after existing ones so ids
    // never collide within the claim file.
    const offset = claimFile.claims.length;
    newClaims = synthesized.claims.map((c, i) => ({
      ...c,
      claim_id: `${questionId}-c${String(offset + i + 1).padStart(2, "0")}`,
    }));
    claimFile.claims.push(...newClaims);
    claimFile.answer_summary = synthesized.answer_summary;
    // Merge disputed aspects (dedupe by source_url).
    const seen = new Set(
      (claimFile.disputed_aspects || []).map((d) => d.source_url)
    );
    for (const d of synthesized.disputed_aspects) {
      if (!seen.has(d.source_url)) {
        claimFile.disputed_aspects.push(d);
        seen.add(d.source_url);
      }
    }
    log(
      `FETCHED ${questionId} via ensemble: ${newClaims.length} claim(s), ` +
        `${synthesized.disputed_aspects.length} disputed`
    );
  } else {
    // ── Single-shot path (default, unchanged) ────────────────────────
    let fresh;
    if (provider) {
      fresh = await provider(questionId, regEntry.question);
    } else if (mock) {
      fresh = mockAnswer(questionId, regEntry.question);
    } else {
      fresh = await liveAnswer(regEntry.question);
    }
    if (!fresh || !fresh.text) {
      log(`FAIL ${questionId}: provider returned no text`);
      throw new Error("Answer provider returned no text.");
    }
    log(
      `FETCHED ${questionId}: ${fresh.text.length} chars, ` +
        `${(fresh.sources || []).length} source(s) via ${fresh.model || "?"}`
    );

    const sources = (fresh.sources || []).map((s) => {
      const { type, credibility } = classifySource(s.url);
      return {
        url: s.url,
        title: s.title || s.url,
        type,
        retrieved: day,
        credibility,
      };
    });

    const nextClaimNum = claimFile.claims.length + 1;
    const newClaim = {
      claim_id: `${questionId}-c${String(nextClaimNum).padStart(2, "0")}`,
      text: fresh.text,
      reliability: "established",
      sources,
      perspectives: [],
      last_verified: day,
      added_edition: newEdition,
    };
    claimFile.claims.push(newClaim);
    claimFile.answer_summary = summarise(fresh.text);
    newClaims = [newClaim];
  }

  claimFile.current_edition = newEdition;
  claimFile.question_text = regEntry.question;

  // 5. Append the immutable ledger entry.
  const wasNew = !existing;
  const authorBase = ensemble ? "ensemble" : "orchestrator";
  ledger.editions.push({
    edition_number: newEdition,
    created_at: nowISO(),
    description: `Refreshed ${questionId} via ${mock ? "mock " : ""}${authorBase}.`,
    questions_updated: wasNew ? [] : [questionId],
    questions_added: wasNew ? [questionId] : [],
    questions_deprecated: [],
    author: mock ? `${authorBase}(mock)` : authorBase,
  });

  // 6. If this question was only "proposed", promote it to active.
  if (regEntry.status === "proposed") {
    regEntry.status = "active";
    if (regEntry.added_in_edition == null) regEntry.added_in_edition = newEdition;
  }

  if (persist) {
    writeJSON(claimFilePath, claimFile);
    writeJSON(PATHS.ledger, ledger);
    writeJSON(PATHS.registry, registry);
  }

  const primaryClaim = newClaims[newClaims.length - 1];
  log(`DONE ${questionId}: wrote edition ${newEdition}, ` +
      `${newClaims.length} claim(s), last ${primaryClaim.claim_id}`);

  return {
    questionId,
    edition: newEdition,
    claim: primaryClaim,
    claims: newClaims,
    claimFile,
    ledger,
  };
}

// ── CLI entry point ─────────────────────────────────────────────────
if (require.main === module) {
  const args = parseArgs(process.argv.slice(2));
  const questionId = args["question-id"];
  const mock = Boolean(args.mock);
  const ensemble = Boolean(args.ensemble);

  orchestrate(questionId, { mock, ensemble })
    .then((r) => {
      console.log(`✓ Refreshed ${r.questionId}`);
      console.log(`  edition : ${r.edition}`);
      console.log(`  claims  : ${r.claims.length} (last ${r.claim.claim_id})`);
      console.log(`  sources : ${r.claim.sources.length}`);
      console.log(`  log     : ${path.relative(PATHS.root, PATHS.orchestrationLog)}`);
    })
    .catch((err) => {
      console.error("✗ Orchestration failed: " + err.message);
      process.exit(1);
    });
}

module.exports = { orchestrate, mockAnswer };
