#!/usr/bin/env bash
# post-batch-push.sh — waits for the batch-refresh job to finish,
# then commits + pushes all refreshed data and the rebuilt site,
# and restarts the Back Office service.
#
# Usage (already launched as background process):
#   nohup bash scripts/post-batch-push.sh 13830 > /tmp/post-batch-push.log 2>&1 &

set -euo pipefail

BATCH_PID="${1:-}"
REPO_DIR="/home/ubuntu/github_repos/living-book"
LOG="/tmp/post-batch-push.log"

log() { echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] $*" | tee -a "$LOG"; }

log "=== POST-BATCH WATCHER STARTED ==="
log "Waiting for batch-refresh PID ${BATCH_PID} to finish…"

# ── 1. Wait for the batch process ─────────────────────────────────────────
if [[ -n "$BATCH_PID" ]]; then
  while kill -0 "$BATCH_PID" 2>/dev/null; do
    sleep 30
  done
  log "Batch PID ${BATCH_PID} has exited."
else
  log "No PID supplied — proceeding immediately."
fi

# ── 2. Give it a few extra seconds to flush file writes ───────────────────
sleep 10

# ── 3. Show batch summary if available ────────────────────────────────────
REPORT="$REPO_DIR/logs/batch-refresh-report.json"
if [[ -f "$REPORT" ]]; then
  log "Batch report summary:"
  python3 -c "
import json, sys
r = json.load(open('$REPORT'))
print(f\"  Total:     {r['total']}\")
print(f\"  Completed: {r['completed']}\")
print(f\"  Skipped:   {r['skipped']}\")
print(f\"  Site rebuilt: {r.get('siteRebuilt', False)}\")
if r.get('errors'):
    print(f\"  Failed: {[e['qid'] for e in r['errors']]}\")
" 2>&1 | while IFS= read -r line; do log "  $line"; done
fi

# ── 4. Get a fresh GitHub token ───────────────────────────────────────────
log "Fetching fresh GitHub access token…"
TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" \
  -H "X-abacus-vm-metadata-token-ttl-seconds: 21600")
ABACUS_API_KEY=$(curl -s -H "X-abacus-vm-metadata-token: $TOKEN" \
  http://169.254.169.254/latest/user-data \
  | python3 -c "import sys,json; print(json.load(sys.stdin)['abacus_api_key'])")

ACCESS_TOKEN=$(curl -s "https://api.abacus.ai/api/getUserConnectorAuth?service=GITHUBUSER" \
  -H "apiKey: ${ABACUS_API_KEY}" \
  | python3 -c "import sys,json; print(json.load(sys.stdin)['result']['auth']['accessToken'])")

if [[ -z "$ACCESS_TOKEN" ]]; then
  log "ERROR: Could not obtain GitHub access token. Aborting push."
  exit 1
fi
log "GitHub token obtained."

git config --global credential.helper store
echo "https://oauth2:${ACCESS_TOKEN}@github.com" > ~/.git-credentials

# ── 5. Stage and commit all refreshed data ────────────────────────────────
cd "$REPO_DIR"

# Make sure git identity is set
git config user.name  "Living Book Bot"
git config user.email "bot@living-book.local"

# Check what changed
CHANGED=$(git status --porcelain | wc -l)
log "Changed/untracked files: ${CHANGED}"

if [[ "$CHANGED" -eq 0 ]]; then
  log "Nothing to commit — working tree is clean."
else
  git add data/claims/ docs/index.html editions/ledger.json logs/batch-refresh-report.json 2>/dev/null || true
  git add -A 2>/dev/null || true

  EDITION=$(python3 -c "
import json
try:
  r = json.load(open('editions/ledger.json'))
  print(len(r.get('editions', [])))
except:
  print('?')
" 2>/dev/null)

  TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M UTC")
  git commit -m "refresh: batch ensemble refresh of all 100 questions — Edition ${EDITION}

All 100 active questions refreshed via the multi-agent ensemble pipeline
(Research Agent → Verification Agent → Synthesis Agent). Each answer is
a 700–900 word, publication-quality essay generated by claude-sonnet-4-6.

- data/claims/ — all 100 claim files updated
- docs/index.html — rebuilt from refreshed data
- editions/ledger.json — edition counter updated
- logs/batch-refresh-report.json — full run statistics

Refreshed: ${TIMESTAMP}" 2>&1 | while IFS= read -r line; do log "  git: $line"; done
fi

# ── 6. Push to GitHub ─────────────────────────────────────────────────────
log "Pushing to origin/main…"
git push origin main 2>&1 | while IFS= read -r line; do log "  push: $line"; done
log "Push complete."

# ── 7. Restart Back Office service ────────────────────────────────────────
log "Restarting living-book-admin service…"
sudo systemctl restart living-book-admin 2>&1 | while IFS= read -r line; do log "  systemctl: $line"; done
sleep 5
STATUS=$(systemctl is-active living-book-admin 2>/dev/null || echo "unknown")
log "Service status after restart: ${STATUS}"

if [[ "$STATUS" == "active" ]]; then
  log "✓ Back Office is running."
else
  log "⚠ Service status is '${STATUS}' — check: journalctl -u living-book-admin -n 30"
fi

log "=== POST-BATCH WATCHER COMPLETE ==="
